### ISSUE TITLE
How to reduce big bundle size?

### ISSUE THREAD

**Issue by jankaderabek** [wobsoriano/vue-clerk#8]
I just noticed that my app bundle size increased a lot after I installed vue-clerk. I can see that it's caused by `@clerk/clerk-js` package and not directly by `vue-clerk`. I saw some commits about experimenting with headless version of clerk but it was reverted after. I would like to ask you what is the state or if you resolved the issue with bundle size somehow different?
Because otherwise this is excellent package and it help me a lot, but this is really a dealbreaker.

<img width="1511" alt="Snímek obrazovky 2023-11-07 v 12 00 14" src="https://github.com/wobsoriano/vue-clerk/assets/7320529/69a30adf-6bdc-4c4e-849e-d398ec637537">

**Comment by wobsoriano** [comment]
Hi! `@clerk/clerk-js` size is that big because it comes with react, as the components use that framework under the hood.

I've experimented with the headless version and reverted it because it removes all the built-in UI components.

I'm still planning on adding support for headless, but users will have to make their own UI components or redirect to the clerk-hosted pages instead.

**Comment by wobsoriano** [comment]
https://github.com/wobsoriano/vue-clerk/pull/37
